name: compile xfrpc in ubuntu-latest 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
          
    - name: compile xfrpc
      run: |
        mkdir build
        cd build
        cmake -D THIRDPARTY_STATIC_BUILD=ON ..
        make
